wandb_version: 1

LSTM1_size:
  desc: null
  value: 100
LSTM2_size:
  desc: null
  value: 70
_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650182011
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.14
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: ReLU
dropout_rate:
  desc: null
  value: 0.2
optimizer:
  desc: null
  value: Adam
